# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_imagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(verbose_name='Data de cadastro')),
                ('path_imagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
        ),
    ]
