# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20170203_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueproduto',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.TipoProduto'),
            preserve_default=False,
        ),
    ]
