# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20170203_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproduto',
            name='mnemonico',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
