# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_tipoproduto_mnemonico'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueproduto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
