# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20170211_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default='EYK', max_length=10),
            preserve_default=False,
        ),
    ]
