# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_produto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo',
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='codigo',
            field=models.CharField(default='EYK', max_length=5),
            preserve_default=False,
        ),
    ]
