# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20170211_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoqueproduto',
            name='preco_sem_desconto',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
